
version: "3"

networks:
    network:
        driver: bridge

volumes:
    wordpress-vol:
        driver: local
        driver_opts:
            type : none
            o: bind
            device: /home/ynakamot/data/wordpress

services:
    nginx:
        build:
            context: ./requirements/nginx
            args:
                DOMAIN_NAME: ${DOMAIN_NAME}
        image: nginx:ynakamot
        container_name: nginx
        restart: always
        depends_on:
            - wordpress
        ports:
            - "443:443"
        networks:
            - network
        volumes:
            - wordpress-vol:/var/www/html

    wordpress:
        build:
            context: ./requirements/wordpress
            args:
                MYSQL_DATABASE: ${MYSQL_DATABASE}
                MYSQL_USER: ${MYSQL_USER}
                MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        image: wordpress:ynakamot
        container_name: wordpress
        restart: always
        depends_on:
            - mariadb
        networks:
            - network
        volumes:
            - wordpress-vol:/var/www/html

    mariadb:
        build:
            context: ./requirements/mariadb
        image: mariadb:ynakamot
        container_name: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_CHARSET: ${MYSQL_CHARSET}
            MYSQL_COLLATION: ${MYSQL_COLLATION}
        networks:
            - network
        volumes:
            - /home/ynakamot/data/mariadb:/var/lib/mysql

    static_website:
        build:
            context: ./requirements/bonus/static_website
        image: static_website:ynakamot
        container_name: static_website
        restart: always
        networks:
            - network