
version: "3"

networks:
    network:
        driver: bridge
    redis-network:
        driver: bridge

volumes:
    wordpress-vol:
        driver: local
        driver_opts:
            type : none
            o: bind
            device: /home/ynakamot/data/wordpress
    mariadb-vol:
        driver: local
        driver_opts:
            type : none
            o: bind
            device: /home/ynakamot/data/mariadb

services:
    nginx:
        build:
            context: ./requirements/nginx
            args:
                DOMAIN_NAME: ${DOMAIN_NAME}
        image: nginx:ynakamot
        container_name: nginx
        restart: always
        depends_on:
            - wordpress
        ports:
            - "443:443"
        networks:
            - network
        volumes:
            - wordpress-vol:/var/www/html

    wordpress:
        build:
            context: ./requirements/wordpress
            args:
                MYSQL_DATABASE: ${MYSQL_DATABASE}
                MYSQL_USER: ${MYSQL_USER}
                MYSQL_PASSWORD: ${MYSQL_PASSWORD}
                DOMAIN_NAME: ${DOMAIN_NAME}
        image: wordpress:ynakamot
        container_name: wordpress
        restart: always
        environment:
            ADMIN_USER: ${ADMIN_USER}
            ADMIN_MAIL: ${ADMIN_MAIL}
            ADMIN_PASS: ${ADMIN_PASS}
            AUTHOR_USER: ${AUTHOR_USER}
            AUTHOR_MAIL: ${AUTHOR_MAIL}
            AUTHOR_PASS: ${AUTHOR_PASS}
            DOMAIN_NAME: ${DOMAIN_NAME}
        depends_on:
            - mariadb
            - redis
        networks:
            - network
            - redis-network
        volumes:
            - wordpress-vol:/var/www/html

    mariadb:
        build:
            context: ./requirements/mariadb
            args:
                MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
                MYSQL_DATABASE: ${MYSQL_DATABASE}
                MYSQL_USER: ${MYSQL_USER}
                MYSQL_PASSWORD: ${MYSQL_PASSWORD}
                MYSQL_CHARSET: ${MYSQL_CHARSET}
                MYSQL_COLLATION: ${MYSQL_COLLATION}
        image: mariadb:ynakamot
        container_name: mariadb
        restart: always
        networks:
            - network
        volumes:
            - mariadb-vol:/var/lib/mysql

#bonus
    static_website:
        build:
            context: ./requirements/bonus/static_website
        image: static_website:ynakamot
        container_name: static_website
        restart: always
        networks:
            - network

    redis:
        build:
            context: ./requirements/bonus/redis
        image: redis:ynakamot
        container_name: redis
        restart: always
        networks:
            - redis-network
