#confirm restart setting

version: "3.8"
services:
    nginx:
        build:
            context: ./requirements/nginx
            args:
                DOMAIN_NAME: ${DOMAIN_NAME}
        image: nginx:ynakamot
        container_name: nginx
        restart: always
        depends_on:
            - wordpress
        ports:
            - "443:443"
        networks:
            - network
        volumes:
            - /home/ynakamot/data/wordpress:/var/www/html
            - /home/ynakamot/data/document:/var/www/document

    wordpress:
        build:
            context: ./requirements/wordpress
        image: wordpress:ynakamot
        container_name: wordpress
        restart: always
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        depends_on:
            - mariadb
        networks:
            - network
        volumes:
            - /home/ynakamot/data/wordpress:/var/www/html

    mariadb:
        build:
            context: ./requirements/mariadb
        image: mariadb:ynakamot
        container_name: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_CHARSET: ${MYSQL_CHARSET}
            MYSQL_COLLATION: ${MYSQL_COLLATION}
        networks:
            - network
        volumes:
            - /home/ynakamot/data/mariadb:/var/lib/mysql

networks:
    network:
        driver: bridge
