version: "3.8"
services:
    nginx:
        build:
            context: ./requirements/nginx
        container_name: nginx
        depends_on:
            - wordpress
        ports:
            - "443:443"
        volumes:
            - ./requirements/wordpress/wp_site:/var/www/html
    wordpress:
        build:
            context: ./requirements/wordpress
        container_name: wordpress
        depends_on:
            - mariadb
        volumes:
            - ./requirements/wordpress/wp_site:/var/www/html
    mariadb:
        build:
            context: ./requirements/mariadb
        init: True
        container_name: mariadb
        # volumes:
        #     - ./requirements/mariadb/db:/var/lib/mysql