version: "3.8"
services:
    nginx:
        build:
            context: ./requirements/nginx
        container_name: nginx
        restart: always
        depends_on:
            - wordpress
        ports:
            - "443:443"
        volumes:
            - ./requirements/wordpress/wp_site:/var/www/html

    wordpress:
        build:
            context: ./requirements/wordpress
        container_name: wordpress
        restart: always
        depends_on:
            - mariadb
        volumes:
            - ./requirements/wordpress/wp_site:/var/www/html

    mariadb:
        build:
            context: ./requirements/mariadb
        container_name: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_CHARSET: ${MYSQL_CHARSET}
            MYSQL_COLLATION: ${MYSQL_COLLATION}
        volumes:
            - ./requirements/mariadb/db:/var/lib/mysql